In [19]:
import numpy as np
import pandas as pd

Задание 1

In [31]:
def cycle(N, k):
    a = list(np.arange(1, k+1))
    n = N // k
    f = N % k
    X = np.array(a*n)
    X = np.append(X, a[:f])
    print(X)
print(cycle(10, 3))

[1 2 3 1 2 3 1 2 3 1]
None


Задание 5

In [21]:
def nearest_value(array, number):
    array = array.ravel()
    print(array)
    idx = np.abs(array - number).argmin()
    return array[idx]
 
X = np.arange(0,10).reshape((2, 5))
v = 3.6
print(X)
print(nearest_value(X, v))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
4


Задание 4

In [10]:
def min_odd(X):
    a = np.array(X)
    print(np.min(a))
X = np.random.randint(10, size=(3, 3))
print(X)
print(min_odd(X))    

[[6 2 3]
 [6 8 1]
 [7 2 5]]
1
None


Задание 2

In [8]:
def next_diagonal(X):
    a = np.array(X)
    p = len(X)
    di = np.diag(a, 1)
    print(di)
X = [1, 2, 3]
print(next_diagonal(X))

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
None
